config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/tasks", to: "tasks#index"
  get "/tasks/new", to: "tasks#new"
  post "/tasks", to: "tasks#create"
  get "/tasks/:id", to: "tasks#show" , as: :task
  get "/tasks/:id/edit", to: "tasks#edit", as: :edit
  patch "/tasks/:id", to: "tasks#update"
  delete "/tasks/:id", to: "tasks#destroy", as: :delete
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    def index #read all
        @tasks = Task.all
        end
    
    def show
        @tasks = Task.find(params[:id])
    end

    def new
        @tasks = Task.new
      end

    def create
        @tasks = Task.new(task_params)
        @tasks.save
    
        redirect_to tasks_path(@tasks)
      end
    
      def edit
        @tasks = Task.find(params[:id])
      end


      def update
        @tasks = Task.find(params[:id])
        @tasks.update(task_params)
    
        redirect_to tasks_path(@tasks)
      end
      
      def destroy
        @tasks = Task.find(params[:id])
        @tasks.destroy
    
        redirect_to tasks_path(@tasks)
      end
    
      private
    
      def task_params
        params.require(:task).permit(:title, :details, :completed)
      end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_for(@tasks) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>
<%= link_to "Back to the list", tasks_path %>

app/views/tasks/index.html.erb
<h1> My tasks </h1>
<ul>
  <% @tasks.each do |task| %>
  <li>
  <input type="checkbox">
  <%= link_to task.title, task_path(task) %>
  <%= link_to '🗑️' , delete_path(task), method: :delete, data:{confirm: 'Are you sure you want to delete?'} %>
  </li>
</ul>
<% end %>
  <%= link_to "Add a new task", tasks_new_path %>

app/views/tasks/new.html.erb
<%= form_for(@tasks) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit %>
<% end %>
<%= link_to "Back to the list", tasks_path %>

app/views/tasks/show.html.erb
<h2><%= @tasks.title %></h2>
<p><%= @tasks.details %></p>
<p><%= @tasks.completed%></p>
<%= link_to "Back", tasks_path %>
<%= link_to "Edit the task ", edit_path(@tasks) %>